# Generated by Django 4.0.1 on 2022-04-03 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0002_alter_user_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_dependency', models.BooleanField(default=False, help_text='Check whether next section can be determined depend upon this question')),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.IntegerField(default=0)),
                ('required_number_of_respondent', models.IntegerField()),
                ('number_of_response', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField(help_text='The date the survey becomes inactive')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age', models.IntegerField(blank=True, null=True)),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Both', 'Both'), ('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('allow_unverified_respondents', models.BooleanField(default=False)),
                ('education_levels', models.ManyToManyField(blank=True, null=True, to='access.EducationLevel')),
                ('occupations', models.ManyToManyField(blank=True, null=True, to='access.Occupation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(help_text='Order of this section of the survey relative to other section. Lowest order number indicates the first section.')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.questionnairetype'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.section'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_selected', models.IntegerField(default=0)),
                ('next_section', models.ForeignKey(blank=True, help_text='If the question has dependence, the next section if this choice selected', null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.section')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionnaire')),
            ],
        ),
    ]
