# Generated by Django 4.0.1 on 2022-04-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyrequirement_education_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='survey.questionnairetype'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='survey.section'),
        ),
        migrations.AlterField(
            model_name='report',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='response',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.questionnaire'),
        ),
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='surveyrequirement',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='survey.survey'),
        ),
    ]
