# Generated by Django 4.0.1 on 2022-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_choice_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_section',
            field=models.PositiveIntegerField(blank=True, help_text='If the question has dependence, the next section order number if this choice selected', null=True),
        ),
    ]
