# Generated by Django 4.0.1 on 2022-05-06 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_respondenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='maximum_choice',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='respondenthistory',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respondenthistory',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_history', to='survey.survey'),
        ),
    ]
