# Generated by Django 4.0.1 on 2022-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_questionnaire_maximum_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
