# Generated by Django 4.0.1 on 2022-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_response_response_response_response_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='maximum_decimal_value',
            field=models.FloatField(blank=True, help_text='only for questionnaire type of decimal', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='maximum_integer_value',
            field=models.IntegerField(blank=True, help_text='only for questionnaire type of integer', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='minimum_decimal_value',
            field=models.FloatField(blank=True, help_text='only for questionnaire type of decimal', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='minimum_integer_value',
            field=models.IntegerField(blank=True, help_text='only for questionnaire type of integer', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_decimal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
