# Generated by Django 4.0.1 on 2022-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_user_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='work_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
